### ISSUE TITLE
Unable to acquire actual address for Parallelvej 15a, 9900 Frederikshavn, Denmark

### ISSUE THREAD

**Issue by JosephWLW** [DanmarksAdresser/Dawa#623]
We need to reverse geocode/acquire GPS coordinates for Parallelvej 15a, 9900 Frederikshavn. We can't seem to acquire it, we can, however acquire Parallelvej 15G, 9900 Frederikshavn. What is the reason for this? It is breaking some of the work we are doing.

**Comment by andershessellund** [comment]
Hej Joseph,

In order to help you I need the exact query you are making which does not give you the expected result. The address exists in DAWA:

http://dawa.aws.dk/adgangsadresser?q=Parallelvej%2015a,%209900%20Frederikshavn .

**Comment by JosephWLW** [comment]
Hi Andershessellund,

The query that we are doing are:
https://dawa.aws.dk/datavask/adresser?betegnelse=Parallelvej%2015A,%209900%20Frederikshavn,%20Denmark

We are retrieving the GPS coordinate(koordinater) by getting the href under aktueladresse but in this case, it is not available.

Can we know what is causing the problem?

**Comment by andershessellund** [comment]
Hi Joseph,

This is a bug. It is triggered by the fact that the original address has been deleted and then a new address has been created instead. Unfortunately, our API incorrectly returns the deleted address and not the new one.

I will look into this, but it will probably be a couple of weeks before a fix will be deployed into production. Thank you for your report.

**Comment by andershessellund** [comment]
Upon further investigation, it turns out that this is not actually a bug. The explanation is a bit complicated.

As mentioned, there are two addresses: The now deleted one with id=2ecce5a7-e717-4b45-8781-279f0b9f423b, and a new one with id=d7814d2e-ceb9-41ae-b004-0d8a7a79661c. The one you find is the old one. It no longer exists, it has been deleted. That is why status=2 in the response.

The reason you do not get the new address is that the new address does not match the search text. The address text for the old address is:
Parallelvej 15A, 9900 Frederikshavn

The address text for the new one is:
Parallelvej 15A, 1. 9900 Frederikshavn

Note that the new address has a floor number. Therefore, the new address does not match the search text you provide. If the old address had not existed, you would still get the new address, but with kategori=C, because it is a poor match. However, because the old address matches perfectly, you only get the old address, which you cannot look up on our API.

Note that if you have addresses without floor/suite numbers, you want to use access addresses (adgangsadresser) instead. Also, it would be better to omit the country part, as including the country part results in poorer performance. This gives you the result you want:

https://dawa.aws.dk/datavask/adgangsadresser?betegnelse=Parallelvej%2015A,%209900%20Frederikshavn

**Comment by JosephWLW** [comment]
@andershessellund Thank you very much [=
